#!/bin/bash
TMP_FILE=/tmp/file-$$

while true; 
do
	read -p "Enter channel number:" input
	case ${input} in
		[1-2] ) 
			echo $input | sdnms > $TMP_FILE
			val=$(cat $TMP_FILE)
			printf "Channel changed to: $input \n"
			;;
		    * )
			printf "\n" 
			printf " ------------------------------------------------------- \n"
			printf " Please enter a number: [1]Un-encrypted [2]Encrypted \n"
			printf " ------------------------------------------------------- \n"
			;;	
	esac
done
