#!/bin/sh

SDNMS=sdnms
HOST=localhost
PORT=1234

FILE1=/tmp/sdnms1-$$
FILE2=/tmp/sdnms2-$$
ERROR=/tmp/sdnms-err-$$

GETTEXT="gettext -d sdnms_ui"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

help () {
        echo "Usage: $0 [ host [port] | --help ]"
}

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

if [ $# -eq 1 ]
then
        if [ $1 -eq '--help' ]
        then
                help
                exit -1
        else
                HOST=$1
        fi
elif [ $# -eq 2 ]
then
        PORT=$2
fi
