#!/bin/sh

FILE1=/tmp/sdnms1-$$
FILE2=/tmp/sdnms2-$$
ERROR=/tmp/sdnms-err-$$

GETTEXT="gettext -d sdnms_gui"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end () {
	rm -f $FILE1 $FILE2 $ERROR
	exit
}

while true
do
	$DIALOG --inputbox "`$GETTEXT \"Select a channel (1 OR 2):\"`" 8 35 2> $FILE1 || end
	if cat $FILE1 | sdnms > $FILE2 2>$ERROR
	then
		MSG="`$GETTEXT \"Channel changed. Continue?\"`"
		$DIALOG --yesno "$MSG" 10 35 || end
	else
		MSG="Error:\n\n`cat $ERROR`\n\nContinue?"
		$DIALOG --yesno "$MSG" 10 35 || end
	fi
done






